features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
footer_copyright: ' © Copyright IPCS. All Rights Reserved'
show_information_icon: 1
address: 'New Delhi, India'
contact: 8888888888
mail_id: test@gmail.com
show_social_icon: 1
facebook_url: 'https://www.facebook_url.com/'
twitter_url: 'https://www.twitter_url.com/'
linkedin_url: 'https://www.linkedin_url.com/'
instagram_url: 'https://www.instagram_url.com/'
youtube_url: 'https://www.youtube_url.com/'
banner_display: 1
bg_image:
  - '2'
banner_title: 'Better Solutions For Your Business'
banner_description: 'We are team of talented designers making websites with Bootstrap'
